news_sites:
  eltiempo:
    url: https://www.eltiempo.com    
    queries:
      typelink: 'a'
      homepage_article_links : 'page-link'

  elespectador:
    ur: https://www.elespectador.com
    queries:
      typelink: 'a'
      homepage_article_links : ''

  vanguardialiberal:
    url: https://www.vanguardia.com
    queries:
      typelink: 'a'
      homepage_article_links : ''
