news_sites:
  eltiempo:
    url: https://www.eltiempo.com    
    queries:      
      homepage_article_links : 
        selector: 'page-link'
        type: 'a'
      article_body: 
        selector: 'contenido'
        type: 'p'
      article_title: 
        selector: 'titulo'
        type: 'h1'
      article_datepubli: 
        selector: '.fecha'
        type:
        form: "%d de %B %Y , %I:%M %p"
        locale: 'es-CO.UTF-8'

  elespectador:
    url: https://www.elespectador.com
    queries:
      typelink: 
      homepage_article_links : 
        selector: ".node-title a"
        type: 
      article_body: 
        selector: '.node-body p'
        type: 
      article_title: 
        selector: '.node-title h1'
        type: 
      article_datepubli: 
        selector: '.node-post-date'
        type: 
        form: "%d %b %Y - %I:%M %p"
        locale: 

  vanguardialiberal:
    url: https://www.vanguardia.com
    queries:
      homepage_article_links : 
        selector: ''
        type: 'a'
      article_body: 
        selector: '.paragraph p'
        type: 
      article_title: 
        selector: 'h1 .priority-content'
        type: 
      article_datepubli: 
        selector: '.date'
        type: 
        form: "%A	%d de %B de %Y - %I:%M %p"
        locale: 'es-CO.UTF-8'

